# Generated by Django 5.2 on 2025-05-06 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=300)),
                ('descripcion', models.CharField(default='', max_length=300)),
                ('texturl', models.CharField(default='', max_length=200)),
                ('texestañol', models.CharField(default='', max_length=200)),
                ('texingles', models.CharField(default='', max_length=200)),
                ('publico', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='habilidadverbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_max', models.CharField(default='', max_length=300)),
                ('caliicacion_minima', models.CharField(default='', max_length=300)),
                ('fecha_entrega', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=300)),
                ('descripcion', models.CharField(default='', max_length=300)),
                ('es_general', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tareas', models.ManyToManyField(blank=True, to='core.tareas')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.IntegerField(choices=[(1, 'Maestro'), (2, 'Alumno')], default=2)),
                ('bocabularioasing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bocabulario')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupo')),
                ('tareastes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tareas')),
                ('usr', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
