# Generated by Django 5.0 on 2025-05-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bocabulario',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
