# Generated by Django 5.0 on 2025-05-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bocabulario_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bocabulario',
            old_name='texestañol',
            new_name='texestanol',
        ),
    ]
