# Generated by Django 5.0 on 2025-05-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_texestañol_bocabulario_texestanol'),
    ]

    operations = [
        migrations.CreateModel(
            name='abcedario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texturl', models.CharField(default='', max_length=200)),
                ('texestanol', models.CharField(default='', max_length=200)),
                ('texingles', models.CharField(default='', max_length=200)),
                ('publico', models.BooleanField(default=False)),
            ],
        ),
    ]
