# Generated by Django 5.0 on 2025-06-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_abcedario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='grado_a_impartir',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo_aimpartir',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='materia_a_impartir',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
