# Generated by Django 5.0 on 2025-06-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_grado_a_impartir_usuario_grupo_aimpartir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='grado_a_impartir',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
