# Generated by Django 5.0 on 2025-08-04 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuario_grado_a_impartir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tareastes',
        ),
        migrations.AddField(
            model_name='tareas',
            name='archivo_adjunto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='tareas',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='tareas',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='instrucciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='puntos_maximos',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='TareaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento_personalizada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_PROGRESO', 'En Progreso'), ('ENTREGADA', 'Entregada'), ('REVISADA', 'Revisada'), ('CALIFICADA', 'Calificada')], default='ASIGNADA', max_length=20)),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_realizadas', to='core.usuario')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='core.usuario')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='core.grupo')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.tareas')),
            ],
            options={
                'unique_together': {('tarea', 'estudiante'), ('tarea', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='TareaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('archivo_adjunto', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENTREGADA', 'Entregada'), ('REVISANDO', 'En Revisión'), ('CALIFICADA', 'Calificada')], default='BORRADOR', max_length=20)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.tareaasignacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_realizadas', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TareaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='core.tareaentrega')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_realizadas', to='core.usuario')),
            ],
        ),
    ]
